auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  wal:
    dir: "/tmp/wal"

  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 0

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: /loki/working_directory
  shared_store: filesystem

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  # retention_period: 2160h

  # index_tables_provisioning:
  #   provisioned_write_throughput: 10
  #   provisioned_read_throughput: 5
  #   inactive_write_throughput: 1
  #   inactive_read_throughput: 1
  #   retention_period: 2160h

  # chunk_tables_provisioning:
  #   provisioned_write_throughput: 20
  #   provisioned_read_throughput: 10
  #   inactive_write_throughput: 1
  #   inactive_read_throughput: 1
  #   retention_period: 2160h
