# Disable multi-tenancy, ensuring a single tenant for all log streams.
auth_enabled: false

server:
  http_listen_port: 3100
  log_level: info

limits_config:
  volume_enabled: true
  allow_structured_metadata: true
  retention_period: 2160h

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules

  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

compactor:
  retention_enabled: true
  retention_delete_delay: 30m
  delete_request_store: filesystem
  compaction_interval: 10m

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

#analytics:
#  reporting_enabled: false

ingester:
  wal:
    enabled: true
    dir: /loki/wal # Directory to store the WAL files
    checkpoint_duration: 5m # Interval between checkpoints
    flush_on_shutdown: true # Flush WAL on shutdown
    replay_memory_ceiling: 256MB # Maximum memory used during replay

